### ISSUE TITLE
Add README file

### ISSUE THREAD

**Issue by HaleemaLimbada** [legorovers/pirover_simulator#9]
There is not currently a readme file. This would be useful for people who are new to the codebase

**Comment by louiseadennis** [comment]
Agreed - would you like to be assigned this?

**Comment by Th0ught09** [comment]
I have a lot of experience in markdown, I'd like to if it's on offer? :)

**Comment by louiseadennis** [comment]
@Th0ught09 - It's all yours!

**Comment by suzanneEmbury** [comment]
There are some resources on how to write a good README file, @HaleemaLimbada .  Here are some suggestions, in case they are useful.

https://github.com/hackergrrl/art-of-readme
https://www.makeareadme.com
